module.exports = {
  EVENT: {
    CARD_FLIP: "CARD_FLIP",
    CARD_FLIPPED: "CARD_FLIPPED",
    CONNECTION: "connection",
    CURRENT_PLAYER_SWITCHED: "CURRENT_PLAYER_SWITCHED",
    DISCONNECT: "disconnect",
    GAME_COUNTDOWN_EXPIRED: "GAME_COUNTDOWN_EXPIRED",
    GAME_END: "GAME_END",
    PLAYER_COUNTDOWN_UPDATED: "PLAYER_COUNTDOWN_UPDATED",
    PLAYER_COUNTDOWN_EXPIRED: "PLAYER_COUNTDOWN_EXPIRED"
  },
  ERROR: {
    DISCONNECT: "Sorry, the game was closed due to a connection problem with the server."
  },
  GAME_END_TYPE: {
    WON: "WON",
    LOST: "LOST",
    TIE: "TIE",
    TIMEOUT: "TIMEOUT"
  },
  LOAD_STATUS: {
    LOADED: "LOADED",
    LOADING: "LOADING",
    ERROR: "ERROR",
    GAME_END: "GAME_END",
    PLAYER_TIMEOUT: "PLAYER_TIMEOUT"
  }
};
